###
POST http://localhost:5000/api/users/register
Content-Type: application/json

{
    "name": "Camilo",
    "last_name": "Acosta",
    "email": "camilo@example.com",
    "password": "1234567890"
}

### Login de Usuario
POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
    "email": "camilo@example.com",
    "password": "1234567890"
}