###Resigistro de Usuario
POST http://localhost:5000/api/users/register
Content-Type: application/json

{
    "name": "Camilo",
    "last_name": "Acosta",
    "email": "camilo@example.com",
    "password": "1234567890"
}

### Login de Usuario
POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
    "email": "camilo@example.com",
    "password": "1234567890"
}

###Crear Test
POST http://localhost:5000/api/test/create
Content-Type: application/json

{
    "userId": "666093e0833305946ced845a",
    "name": "Prueba de la prueba",
    "type": "abierto",
    "questions": [
        "Pregunta 1",
        "Pregunta 2"
    ],
    "cards": [
        "Carta 1",
        "Carta 2",
        "Carta 3",
        "Carta 4"
    ],
    "categories": [
        "Categoria 1",
        "Categoria 2"
    ]
}

###Get tests by user
GET http://localhost:5000/api/test/666093e0833305946ced845a

###Get test by access link
GET http://localhost:5000/api/test/solve/b7ba9b223c2e9b46570090fc91b9a843

{
    "userId": "666093e0833305946ced845a",
    "name": "Prueba de la prueba",
    "type": "abierto",
    "solutionId": "666093e0833305946ced845a",
    "userEmail": "email@email.com",
    "answers": [
       {
        "questionId": "indexPregunta",
        "answer": "Respuesta"
       }
    ],
    "solution": {
        "indexCegoria": ["carta1", "carta2", "carta3", "carta4"],
    }
   
}